#-------------------------------
# General Site Settings

menu:
#- {name: 'Projects', url: ''}
#- {name: 'Blog', url: 'pages/blog.html'}
#- {name: 'Sobre mim', url: 'sobre'}
- {name: 'Contatos', url: 'contatos'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

contact: >
  # Entre em contato comigo

  Fale conosco pelo nosso chat! Veja nossa área de atuação antes de realizar um pedido.

#-------------------------------
# Work Section

projects:
- {name: 'Mudas de Babosa', folder: 'proj-1', file: 'mudas_de_babosa'}
- {name: 'Minhas Plantas', folder: 'proj-2', file: 'minhas_plantas'}

#-------------------------------
# Contact Section

social:
 - {icon: 'facebook', link: '#'}
# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
